"""
Antigravity — Report Exporters.

Exports PortfolioEvaluationReport to JSON and Markdown.
Output directory: data/processed/reports/
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timezone

from app.reporting.report_schema import PortfolioEvaluationReport

REPORTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data", "processed", "reports",
)


def export_json(report: PortfolioEvaluationReport) -> str:
    """Export to data/processed/reports/latest_portfolio_evaluation.json."""
    os.makedirs(REPORTS_DIR, exist_ok=True)
    path = os.path.join(REPORTS_DIR, "latest_portfolio_evaluation.json")
    with open(path, "w", encoding="utf-8") as f:
        f.write(report.to_json())
    print(f"  [Evaluator] JSON report → {path}")
    return path


def export_markdown(report: PortfolioEvaluationReport) -> str:
    """Export to data/processed/reports/latest_portfolio_evaluation.md."""
    os.makedirs(REPORTS_DIR, exist_ok=True)
    path = os.path.join(REPORTS_DIR, "latest_portfolio_evaluation.md")

    lines = [
        "# Portfolio Evaluation Report",
        "",
        f"**Generated:** {report.timestamp}",
        f"**Report ID:** {report.report_id}",
        f"**Regime:** {report.regime}",
        f"**Stance:** {report.stance.upper()}",
        f"**Total Signal Score:** {report.total_signal_score:+.2f}",
        f"**Cash Reserve:** {report.cash_pct:.0%}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"**Simple:** {report.simple_summary}",
        "",
        f"**Analyst:** {report.analyst_summary}",
        "",
        f"**Execution:** {report.execution_summary}",
        "",
        "---",
    ]

    # Decision cards
    lines += ["", "## Asset Decisions", ""]
    lines += [
        "| Ticker | Action | Conviction | Engine | Target Wt | Timeframe |",
        "|--------|--------|-----------|--------|-----------|-----------|",
    ]
    for d in report.decisions:
        lines.append(
            f"| {d.ticker} | {d.action} | {d.conviction} | {d.engine} "
            f"| {d.target_weight_pct:.1%} | {d.timeframe} |"
        )

    lines += ["", "---"]

    # Engine evaluations
    for eng in report.engines:
        lines += [
            "",
            f"## {eng.engine_name} — {eng.allocation_pct:.0%} ({eng.stance})",
            "",
            f"{eng.rationale}",
            "",
            f"**Risk:** {eng.risk_summary}",
            "",
        ]
        for h in eng.top_holdings:
            lines += [
                f"### {h.ticker} — {h.action} ({h.conviction})",
                "",
                f"**Thesis:** {h.thesis}",
                "",
                f"**Advantage:** {h.advantage}",
                "",
                f"**Risk:** {h.primary_risk}",
                "",
                f"**Invalidation:** {h.invalidation_trigger}",
                "",
                f"**Entry:** {h.entry_strategy} | **Timeframe:** {h.timeframe}",
                "",
            ]

    # Governance
    lines += [
        "---",
        "",
        "## Governance",
        "",
        f"**Status:** {'✅ PASSED' if report.governance_passed else '⚠️ FAILED'}",
        "",
    ]
    for note in report.governance_notes:
        lines.append(f"- {note}")

    lines += [
        "",
        "---",
        "",
        "*Generated by the Antigravity Portfolio Evaluation Engine.*",
    ]

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  [Evaluator] Markdown report → {path}")
    return path
